### ISSUE TITLE
Search field value?

### ISSUE THREAD

**Issue by Vandemonica** [rynpsc/craft-phone-number#20]
Not really an issue, but is finding entry by this plugin value is possible?

I've tried something like this
```php
Entry::find()->phone("85000000000")->all();
```

and even something silly like this
```php
Entry::find()
    ->phone([
        "number" => "85000000000",
        "region" => "US"
    ])
    ->all();
```

Thanks in advance!

**Comment by rynpsc** [comment]
This isn't currently possible due to how the data is stored. I'll investigate if this is possible.

**Comment by rynpsc** [comment]
This is now possible in [3.0.0-beta.1](https://github.com/rynpsc/craft-phone-number/releases/tag/3.0.0-beta.1) (requires Craft 5).

```twig
{% set entries = craft.entries()
  .phone({
    region: ['GB']
  })
  .all() %}
```

[See the readme full for details](https://github.com/rynpsc/craft-phone-number/tree/3.0.0-beta.1?tab=readme-ov-file#querying-elements-with-phone-number-fields).

Due to the way this works, it's not feasible to port this feature to the Craft 3/4 version.
